- name: build
  tasks:
    - mkdir -p public
    - - npm run html
    - - webpack --config webpack/development.server.js
    - - webpack --config webpack/development.application.js
    - - npm run assets

- name: build
  env: production
  tasks:
    - mkdir -p public
    - - npm run html
    - - webpack --config webpack/development.server.js
    - - webpack --config webpack/production.application.js
    - - npm run assets

- name: watch
  task: npm run build && concurrently 'nodemon public/server.js' 'webpack --config webpack/development.server.js --watch' 'webpack --config webpack/development.application.js --watch' 'node-sass --watch src/sass/index.scss public/assets/css/application.css'
