- name: build
  tasks:
    - mkdir -p public
    - - npm run html
    - - webpack --config webpack/development.server.js
    - - webpack --config webpack/development.application.js
    - - npm run images
    - - npm run sass

- name: build
  env: production
  tasks:
    - mkdir -p public
    - - npm run html
    - - webpack --config webpack/development.server.js
    - - webpack --config webpack/production.application.js
    - - npm run images
    - - npm run sass

- name: watch
  task: npm run build && concurrently 'nodemon public/server.js' 'webpack --config webpack/development.server.js --watch' 'webpack --config webpack/development.application.js --watch' 'taskfile sass --watch'

- name: sass
  tasks:
    - node-sass src/sass/application.scss public/assets/css/application.css --output-style compressed $1
    - node-sass src/sass/contact.scss public/assets/css/contact.css --output-style compressed $1
    - node-sass src/sass/containers/admin/gallery.scss public/assets/css/admin-gallery.css --output-style compressed $1
    - node-sass src/sass/containers/admin/page.scss public/assets/css/admin-page.css --output-style compressed $1
    - node-sass src/sass/containers/admin/login.scss public/assets/css/admin-login.css --output-style compressed $1
    - node-sass src/sass/containers/admin/meta.scss public/assets/css/admin-meta.css --output-style compressed $1
    - node-sass src/sass/containers/admin/pages.scss public/assets/css/admin-pages.css --output-style compressed $1
    - node-sass src/sass/containers/admin/galleries.scss public/assets/css/admin-galleries.css --output-style compressed $1

- name: lint
  tasks:
    - xo src/js/*.js src/js/**/*.js src/js/**/**/*.js src/js/**/**/**/*.js
     - - xo server/js/*.js server/js/**/*.js server/js/**/**/*.js server/js/**/**/**/*.js
    - - - stylelint src/sass/*.scss src/sass/**/*.scss