language: node_js
node_js: stable
script:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: YrplZbl45O4312wbHNnzlE0ZAcOwITnAQvGpJca0Ot72He8Xlf/CvCTVzX03FFC+TgtJCQMmdFiH3zbd094cnCluMkeYsYCY8Ic2cmuoqaouCu4U42JlO+cOy3SM4sCKSeE4mFLJxl3mdhWMeuhKFoeRNjGdvfkAmnoZ/fsWQj3KoFJ/4JYpSP0tSF3B1+S9EXnoI1KP2/ZjSSI0gTv4MzUEG9Lc7s2vXcDpklg/SpUiOg2sC/livyDS+HHkFkf5hnqlHm5jECVieCt4yarCoxu5BjMSpZC44X9EAcr8QdaLkLvY4YsUNjCWj7ttdeCjO3E8914IUJiV5WVh1NQTV/vOrTBby+Ga4bH55DQviBDED2uK0f31erVYS9cHqGHFXmjmXBiCGlYYomcGcigETi8glaTxI6ug5oIOJF7ZTWfJMjRhp+LpBObT8vLe8MRQLiVq8/BKMLlj5lLIvD5gs07bSVBbdUJbg3NadQTmeyzIRRfkZThNpc+R8Gwq9odV6mH/gbmg/NSJEU5d8YdJBTmwUJ6ma31nawDvewjrkN+11bcE4zWADBhcnDeK5KWGXoq/zbY3uKFBLDYho3T0AnNffjbgy+CuVWcxE+XSOVZvV6IeMoIRyWkJ2Z8v3i20aOLfgFvlAAEM4/yupIUQP/R9vTbYx8jpygUsIIdw9Rg=
  app: carpet-base
  on:
    repo: Pture/CarpetBase
