language: node_js
node_js: stable
script:
- npm install
- npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: LiuIc4V/Ms0ciW7kcHzyyS92Wn6CqlUjzvN6WGR9VLM24PFQhRS1dELexqFY8xb7WqLuS8yYsqnaXP/frTP7KRUY6HbnmC0bmULYNytH91mZIoCwXxdRllCauvTNWAzCwrHd7L6w/KNMlbaNkOosMphCWWnY6EPtVjyQvyfw+d3ZUeBo7h31n8GQuBUDHlHZy6URIwid4M4OS3JND5gvraZb0yYUgXq0AbAiMEmBp3KLAxuOf1yCRRntNTI0/0UAv5pOUm0H9g+sKmHdihMcbWL1ha6ikVn4rGZjHObdeckUFTrM6B16LHnUk9vm4zCwizYzq51LZqwHE8jSgLGah1ZtbQU/vcg5Z3rzbsO414+LkFY0VID6FwyYzyvLBvHKniraKxFBR0SeACRxdcQbeUJiQ/QIBdkqif3hR0ykjtFFYwIMhC6eP9v1J6ptJUIIv0B19aNj7t3mnFTxoJ/OuhguWUokRmZTzv9ZiBip2i/QpBJF1oCE3mxo3tp2d59aYVvV+eudnrjIlG9Dk9vOjbLvYEoxk/lHpuVKdWqM2jwXPPHig7g8ybMd8/sYawMUfqLoQriY58x7fgJEBLPcYXhElcAwjpLvH9Ju2PSLldboEhtmEg/NVBS0ttTk+Uam77//3+8G/ewRHpDrKOLUiKCIkQDusp+OdUXleCBShzI=
  app: carpet-base
  on:
    repo: Pture/CarpetBase
